name = "BasicInterpolators"
uuid = "26cce99e-4866-4b6d-ab74-862489e035e0"
authors = ["Mark Baum <markmbaum@protonmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
