name = "BasicInterpolators"
uuid = "26cce99e-4866-4b6d-ab74-862489e035e0"
authors = ["Mark Baum <markmbaum@protonmail.com>"]
version = "0.3.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
